auto updates subs by repeater, changed funcs a bit
gotohe11/bot_get_issues pull request #1
Opened 2024-09-20 15:19 UTC by gotohe11

2024-09-23 06:59 UTC, protoss-player requested changes
В целом вроде и норм, если не считать пары небольших правок.

2024-09-23 06:59 UTC, protoss-player commented on logic/cli.py
> +        if user.subs:
Что-то код вправо унесло

2024-09-23 06:59 UTC, protoss-player commented on logic/cli.py
> +        if numbers_new_issues_list:
Кажется, код дублируется с блоком `if not since_date`. Точно нельзя обобщить его на оба случая?

2024-09-23 08:45 UTC, gotohe11 commented on logic/cli.py
> +        if user.subs:
+

2024-09-23 12:16 UTC, gotohe11 commented on logic/cli.py
> +        if numbers_new_issues_list:
чуток поменяла, короче не стало, но уже без дублирования

2024-10-03 05:40 UTC, protoss-player approved these changes

2024-10-04 08:33 UTC, merged